/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'daou' at '16. 11. 28 오전 9:29' with Gradle 2.14.1
 *
 * @author daou, @date 16. 11. 28 오전 9:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
